baseURL = "https://recipes.danielcorin.com/"
languageCode = "en-us"
title = "Silmarie and Dan's Recipe Book"
theme = "recipes"

[params]
  author = "Dan Corin"
  description = "Silmarie and Dan's Recipe Book"